### ISSUE TITLE
for calcs using Duan EOS like pf.calculate_entrapment_P_XH2O, P_kbar_mixCO2_DZ06_Hloss drops from 40 kbar to 1 then negative at high rho CO2 and temp. 

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#61]
this may just be limits PTrho and the EOS but it seems something odd is going on with the "P_kbar_mixCO2_DZ06_Hloss column at certain conditions (here 1150 C, rho >1.494, P>30.88 kbar pure). It doesn't happen with the no_Hloss column. (P goes from 40 kbar to 1 and at higher T it goes negative).
![image](https://github.com/PennyWieser/DiadFit/assets/103474333/e74f8496-b4af-4c0a-a4e1-b034483cf95e)

**Comment by PennyWieser** [comment]
Issue with newson-raphson converge method. Certain T  -XH2O-P conditions (particularly at higher densities) yielded very low or negative pressures. Now, use a look up table for initial conditoins. Note, some conditions will now return nan as the molar volume is negative, which isnt possible. Should be fixed in v. 85
